language: cpp
os: osx
osx_image: xcode10.2
compiler: clang

cache:
  ccache: true
  directories:
  - "$HOME/Library/Caches/Homebrew"
before_cache:
- brew cleanup

stages:
- name: test
  if: type IN (pull_request) OR tag IS present
- name: deploy
  if: tag IS present

jobs:
  include:
  - stage: test
    script:
    - "./.travis/install-deps.sh"
    - export PATH="/usr/local/opt/ccache/libexec:$PATH";
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug
    - cmake --build .
    - ctest -V
  - stage: deploy
    script:
    - "./.travis/install-deps.sh"
    - export PATH="/usr/local/opt/ccache/libexec:$PATH";
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build .
    - cmake --build . --target bundle
    deploy:
      provider: releases
      skip_cleanup: true
      api_key:
        secure: f+KNCmqcOgXvhx4isQaXbALiHbSZ7YslkNUL4dnIWI0hf3uoLeXC7tDYNhkvJ4Q6d2NLMBs7Ss6uweJu+LbiS87cqez+EMrGPIw1n3s0pqxlxmFiN4E1WVYsVb550Jt9ZdnxT9J3ZdRYE69r3chsaNr7ShZvNaiGJj6Oi6rivAyNOIPK0NADmbK1tFa96BgTBHoPxDaiIQQuclpkVx3QpPm9PGqhbpFmflbdkfSIXW5zb7+VOmFlNt6FxOh3d8idE6Zr7EMT4X/klD0oqYMtQ23TnSc6O15aKWN7Rn5gU3MVrG2p7055O/M6CQfFLfIMlBLww65TqgaKnzH7WIRO4EWLM1kgmZmaElzzRLVVct9sSUmQvcLyIEJice2rBLPUPYYJvPwcTN43aAUq6HcKuAS15LMroZXmKOr0ZH6Vi3J8I07L3tNSXyV17+zSU3bCaB2sf9advlr6PeEd/NRewhEwYnVsazt0YUL7VkSKH6mdtxbnyoiQVWAvFctA6YKq5OduoakqVzwd4O7hWZHQ1pU5ILQ2T0hRqtrh98uumWYctGvDXptIcbhG9lB8D4LUrCNuDDNOhi+QTPYcrKEifEzTyrEnrUNmLKcfULwYm0ylh01IEFgwOZpcPyxVRyccw4EUzZgUQvNTR4Gd4pi0/jMIPxlH+QADcj8KTIr7h/Q=
      file: src/ELook.dmg
      on:
        branch: master
        tags: true
